const MyButton = [
    {
        id: "0", title: "فہرست مضامین", page: 1
    },
    { id: "1", title: "ایمان مجمل", page: 4 },
    { id: "2", title: "ایمان مفصل", page: 5 },
    { id: "3", title: "اول کلمہ", page: 6 },
    { id: "4", title: "دوم کلمہ", page: 7 },
    { id: "5", page: 8, title: "سوم کلمہ" },
    { id: "6", page: 9, title: "چہارم کلمہ" },
    { id: "7", page: 10, title: "پنجم کلمہ" },
    { id: "8", page: 11, title: "ششم کلمہ" },
    { id: "9", page: 12, title: "غسل" },
    { id: "10", page: 13, title: "وضو سے پہلے کی دعا" },
    { id: "11", page: 14, title: "وضو کرنے کا طریقہ" },
    { id: "12", page: 15, title: "ہاتھوں کا دھونا" },
    { id: "13", page: 16, title: "کلی کرنا" },
    { id: "14", page: 17, title: "ناک صاف کرنا" },
    { id: "15", page: 18, title: "چہرہ دھونا" },
    { id: "16", page: 19, title: "وضو کے درمیان کی دعا" },
    { id: "17", page: 20, title: "بازو دھونا" },
    { id: "18", page: 21, title: "مسح کرنا" },
    { id: "19", page: 22, title: "پاؤں دھونا" },
    { id: "20", page: 23, title: "وضو کے اہم نکات" },
    { id: "21", page: 24, title: "وضو توڑنے والی چیزیں" },
    { id: "22", page: 25, title: "وضو کے فرائض" },
    { id: "23", page: 26, title: "نماز کے شرطیں" },
    { id: "24", page: 27, title: "نماز کے فرائض" },
    { id: "25", page: 28, title: "رکعات کی تفصیل" },
    { id: "26", page: 29, title: "مکمل نماز نیت" },
    { id: "27", page: 30, title: "تکبیر تحریمہ" },
    { id: "28", page: 31, title: "قیام" },
    { id: "29", page: 32, title: "تعوذ،تسمیہ" },
    { id: "30", page: 33, title: "سورۃ الفاتحہ" },
    { id: "31", page: 34, title: "قرات" },
    { id: "32", page: 35, title: "رکوع" },
    { id: "33", page: 36, title: "قومہ" },
    { id: "34", page: 37, title: "سجدہ" },
    { id: "35", page: 38, title: "جلسہ" },
    { id: "36", page: 39, title: "قعدہ-تشہد - حصہ 1" },
    { id: "37", page: 40, title: "قعدہ-تشہد - حصہ 2" },
    { id: "38", page: 41, title: "درودابراھیمی" },
    { id: "39", page: 42, title: "دعا" },
    { id: "40", page: 43, title: "سلام" },
    { id: "41", page: 44, title: "سجدہ سھو" },
    { id: "42", page: 45, title: "نفلی نمازوں کا فاںدہ" },
    { id: "43", page: 46, title: "نماز تحۃ الوضو " },
    { id: "44", page: 47, title: "نماز تحیۃ المسجد" },
    { id: "45", page: 48, title: "نماز تہجد" },
    { id: "46", page: 49, title: "نماز اشراق" },
    { id: "47", page: 50, title: "نماز چاشت" },
    { id: "48", page: 51, title: "نماز اوابین" },
    { id: "49", page: 52, title: "صلوٰۃ التوبہ" },
    { id: "50", page: 53, title: "صلوٰۃالحاجۃ" },
    { id: "51", page: 54, title: "صلوٰۃ استخارہ" },
    { id: "52", page: 55, title: "نماز تراویح" },
    { id: "53", page: 55, title: "نماز تراویح" },
    { id: "54", page: 56, title: "نماز وتر" },
    { id: "55", page: 57, title: "نماز سفر" },
    { id: "56", page: 58, title: "نماز قصر" },
    { id: "57", page: 59, title: "نماز قضاء" },
    { id: "58", page: 60, title: "نماز تسبیح کی فضیلت" },
    { id: "59", page: 61, title: "نماز تسبیح" },
    { id: "60", page: 62, title: "نماز کسوف" },
    { id: "61", page: 63, title: "نماز استسقاء" },
    { id: "62", page: 64, title: "نماز عید" },

]
export { MyButton }

